# Generated by Django 5.2.7 on 2025-11-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0002_alter_cryptotransaction_amount_ngn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptotransaction',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
